site_name: ProxiMarkt. Mercat de proximitat.
theme: 
  name: material
  logo: img/logo.svg
  palette:
    primary: 'deep purple'

markdown_extensions:
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true

plugins:
  - search
  - replace_ra_ca

extra_css:
  - assets/stylesheets/custom.css

# Per activat el plugin replace_ra_ca cal
# $ cd my_plugins/
# (venv) ...Exemples/ProxiMarkt/my_plugins$ pip install -e .
# El plugin necessita instal·lar pandas en l'entorn virtual
# (venv) j$ pip install pandas
# (venv) j$ pip install odfpy